// Copyright 2023 The Libc Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package libc provides run time support for programs generated by the
// [ccgo] C to Go transpiler, version 4 or later.
//
// # Bugs
//
// A subset of musl v0.6.0, beta version from 2011, is exported.
//
// Only a single instance of TLS exists. All calls to NewTLS return the same
// instance.
//
// As a consequnce from the previous point, there's no concurrency support yet.
// All client calls into libc must return before issuing any other call into
// libc.
//
// environ is not supported.
//
// [ccgo]: http://modernc.org/ccgo/v4
package libc // import "modernc.org/libc/v2"
